name: Basic CI Pipeline

on:
  push:
    branches:
      - feature/*
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: python:3.11

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Run simple test
        run: |
          echo "Running CI test..."
          cat test.txt

      - name: Run test script
        # if: github.event_name == 'pull_request' || github.base_ref == 'main'
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          python test3.py || echo "No test file"