name: Basic CI Pipeline

on:
  push:
    branches:
      - feature/*
      - main
  pull_request:
    branches:
      - main

env:
  APP_NAME: my-app
  ENVIRONMENT: dev

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: python:3.11

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Run simple test
        run: |
          echo "Running CI test..."
          echo "Testing Pilpeline"
          cat test.txt
          echo "Repo variable1 is: ${{ vars.REPO_VAR1 }}"
          echo "Local variable app_name: $APP_NAME"
          echo "Dev env variable1 is: ${{ vars.DEV_ENV_VAR1 }}"


      - name: Run test script
        # if: github.event_name == 'pull_request' || github.base_ref == 'main'
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          python test3.py || echo "No test file"